name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Update Dependencies
        run: composer update

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader


      - name: Run Tests
        run: php artisan test

      - name: Set Up SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      - name: Install Git
        run: |
          if ! command -v git &> /dev/null
          then
            echo "Git not found, installing..."
            sudo apt update
            sudo apt install git -y
          else
            echo "Git is already installed"
          fi

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Deploy to EC2
        run: |
          ssh -tt -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} /bin/bash << 'EOF'
            cd /var/www/html/pal
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
        env:
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
