name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Update Dependencies
        run: composer update

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader


      - name: Run Tests
        run: php artisan test

      - name: Set Up SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
      - name: Install Git and Composer on EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            # Update system packages
            sudo dnf update -y

            # Install Git
            sudo dnf install git -y

            # Install PHP and required extensions
            sudo dnf install -y php-cli php-json php-zip curl unzip

            # Install Composer
            curl -sS https://getcomposer.org/installer -o composer-setup.php
            HASH="$(curl -sS https://composer.github.io/installer.sig)"
            php -r "if (hash_file('sha384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
            rm composer-setup.php

            # Navigate to project directory
            #cd /var/www/html/pal
            #git pull origin main
            # Install PHP dependencies
            #composer install --no-dev --optimize-autoloader
            #chmod +x artisan
            # Run migrations
            #php artisan migrate --force
          EOF

      - name: Deploy to EC2
        run: |
          ssh -tt -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/html/pal
            git init
            git remote add origin https://github.com/pal-php/CiCdLaravel.git
            git pull origin main
            git clone https://github.com/pal-php/CiCdLaravel.git
            composer install --no-dev --optimize-autoloader
            chmod +x artisan
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
        env:
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
